services:
  postgres:
    image: postgres:latest
    container_name: Psql
    environment:
      - POSTGRES_USER=xpriori
      - POSTGRES_PASSWORD=phtn458
      - POSTGRES_DB=dpqb
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
