// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fast/ent/account"
	"fast/ent/group"
	"fast/ent/predicate"
	"fast/ent/user"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (gu *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GroupUpdate) SetName(s string) *GroupUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableName(s *string) *GroupUpdate {
	if s != nil {
		gu.SetName(*s)
	}
	return gu
}

// SetNickname sets the "nickname" field.
func (gu *GroupUpdate) SetNickname(s string) *GroupUpdate {
	gu.mutation.SetNickname(s)
	return gu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableNickname(s *string) *GroupUpdate {
	if s != nil {
		gu.SetNickname(*s)
	}
	return gu
}

// SetEmail sets the "email" field.
func (gu *GroupUpdate) SetEmail(s string) *GroupUpdate {
	gu.mutation.SetEmail(s)
	return gu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableEmail(s *string) *GroupUpdate {
	if s != nil {
		gu.SetEmail(*s)
	}
	return gu
}

// SetPhoneNumber sets the "phone_number" field.
func (gu *GroupUpdate) SetPhoneNumber(s string) *GroupUpdate {
	gu.mutation.SetPhoneNumber(s)
	return gu
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (gu *GroupUpdate) SetNillablePhoneNumber(s *string) *GroupUpdate {
	if s != nil {
		gu.SetPhoneNumber(*s)
	}
	return gu
}

// SetPhotoURL sets the "photo_url" field.
func (gu *GroupUpdate) SetPhotoURL(s string) *GroupUpdate {
	gu.mutation.SetPhotoURL(s)
	return gu
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (gu *GroupUpdate) SetNillablePhotoURL(s *string) *GroupUpdate {
	if s != nil {
		gu.SetPhotoURL(*s)
	}
	return gu
}

// SetUID sets the "uid" field.
func (gu *GroupUpdate) SetUID(s string) *GroupUpdate {
	gu.mutation.SetUID(s)
	return gu
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableUID(s *string) *GroupUpdate {
	if s != nil {
		gu.SetUID(*s)
	}
	return gu
}

// SetGroupCode sets the "group_code" field.
func (gu *GroupUpdate) SetGroupCode(s string) *GroupUpdate {
	gu.mutation.SetGroupCode(s)
	return gu
}

// SetNillableGroupCode sets the "group_code" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableGroupCode(s *string) *GroupUpdate {
	if s != nil {
		gu.SetGroupCode(*s)
	}
	return gu
}

// SetAccountID sets the "account_id" field.
func (gu *GroupUpdate) SetAccountID(u uuid.UUID) *GroupUpdate {
	gu.mutation.SetAccountID(u)
	return gu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableAccountID(u *uuid.UUID) *GroupUpdate {
	if u != nil {
		gu.SetAccountID(*u)
	}
	return gu
}

// SetAddress sets the "address" field.
func (gu *GroupUpdate) SetAddress(s string) *GroupUpdate {
	gu.mutation.SetAddress(s)
	return gu
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableAddress(s *string) *GroupUpdate {
	if s != nil {
		gu.SetAddress(*s)
	}
	return gu
}

// ClearAddress clears the value of the "address" field.
func (gu *GroupUpdate) ClearAddress() *GroupUpdate {
	gu.mutation.ClearAddress()
	return gu
}

// SetIsActive sets the "is_active" field.
func (gu *GroupUpdate) SetIsActive(b bool) *GroupUpdate {
	gu.mutation.SetIsActive(b)
	return gu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (gu *GroupUpdate) SetNillableIsActive(b *bool) *GroupUpdate {
	if b != nil {
		gu.SetIsActive(*b)
	}
	return gu
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (gu *GroupUpdate) AddUserIDs(ids ...uuid.UUID) *GroupUpdate {
	gu.mutation.AddUserIDs(ids...)
	return gu
}

// AddUsers adds the "users" edges to the User entity.
func (gu *GroupUpdate) AddUsers(u ...*User) *GroupUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gu.AddUserIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (gu *GroupUpdate) SetAccount(a *Account) *GroupUpdate {
	return gu.SetAccountID(a.ID)
}

// Mutation returns the GroupMutation object of the builder.
func (gu *GroupUpdate) Mutation() *GroupMutation {
	return gu.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (gu *GroupUpdate) ClearUsers() *GroupUpdate {
	gu.mutation.ClearUsers()
	return gu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (gu *GroupUpdate) RemoveUserIDs(ids ...uuid.UUID) *GroupUpdate {
	gu.mutation.RemoveUserIDs(ids...)
	return gu
}

// RemoveUsers removes "users" edges to User entities.
func (gu *GroupUpdate) RemoveUsers(u ...*User) *GroupUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gu.RemoveUserIDs(ids...)
}

// ClearAccount clears the "account" edge to the Account entity.
func (gu *GroupUpdate) ClearAccount() *GroupUpdate {
	gu.mutation.ClearAccount()
	return gu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GroupUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GroupUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gu *GroupUpdate) check() error {
	if v, ok := gu.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := gu.mutation.Nickname(); ok {
		if err := group.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Group.nickname": %w`, err)}
		}
	}
	if v, ok := gu.mutation.Email(); ok {
		if err := group.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Group.email": %w`, err)}
		}
	}
	if v, ok := gu.mutation.PhoneNumber(); ok {
		if err := group.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Group.phone_number": %w`, err)}
		}
	}
	if v, ok := gu.mutation.PhotoURL(); ok {
		if err := group.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "Group.photo_url": %w`, err)}
		}
	}
	if v, ok := gu.mutation.UID(); ok {
		if err := group.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Group.uid": %w`, err)}
		}
	}
	if v, ok := gu.mutation.GroupCode(); ok {
		if err := group.GroupCodeValidator(v); err != nil {
			return &ValidationError{Name: "group_code", err: fmt.Errorf(`ent: validator failed for field "Group.group_code": %w`, err)}
		}
	}
	if v, ok := gu.mutation.Address(); ok {
		if err := group.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Group.address": %w`, err)}
		}
	}
	if gu.mutation.AccountCleared() && len(gu.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.account"`)
	}
	return nil
}

func (gu *GroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := gu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := gu.mutation.Nickname(); ok {
		_spec.SetField(group.FieldNickname, field.TypeString, value)
	}
	if value, ok := gu.mutation.Email(); ok {
		_spec.SetField(group.FieldEmail, field.TypeString, value)
	}
	if value, ok := gu.mutation.PhoneNumber(); ok {
		_spec.SetField(group.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := gu.mutation.PhotoURL(); ok {
		_spec.SetField(group.FieldPhotoURL, field.TypeString, value)
	}
	if value, ok := gu.mutation.UID(); ok {
		_spec.SetField(group.FieldUID, field.TypeString, value)
	}
	if value, ok := gu.mutation.GroupCode(); ok {
		_spec.SetField(group.FieldGroupCode, field.TypeString, value)
	}
	if value, ok := gu.mutation.Address(); ok {
		_spec.SetField(group.FieldAddress, field.TypeString, value)
	}
	if gu.mutation.AddressCleared() {
		_spec.ClearField(group.FieldAddress, field.TypeString)
	}
	if value, ok := gu.mutation.IsActive(); ok {
		_spec.SetField(group.FieldIsActive, field.TypeBool, value)
	}
	if gu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !gu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if gu.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.AccountTable,
			Columns: []string{group.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.AccountTable,
			Columns: []string{group.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetName sets the "name" field.
func (guo *GroupUpdateOne) SetName(s string) *GroupUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableName(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetName(*s)
	}
	return guo
}

// SetNickname sets the "nickname" field.
func (guo *GroupUpdateOne) SetNickname(s string) *GroupUpdateOne {
	guo.mutation.SetNickname(s)
	return guo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableNickname(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetNickname(*s)
	}
	return guo
}

// SetEmail sets the "email" field.
func (guo *GroupUpdateOne) SetEmail(s string) *GroupUpdateOne {
	guo.mutation.SetEmail(s)
	return guo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableEmail(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetEmail(*s)
	}
	return guo
}

// SetPhoneNumber sets the "phone_number" field.
func (guo *GroupUpdateOne) SetPhoneNumber(s string) *GroupUpdateOne {
	guo.mutation.SetPhoneNumber(s)
	return guo
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillablePhoneNumber(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetPhoneNumber(*s)
	}
	return guo
}

// SetPhotoURL sets the "photo_url" field.
func (guo *GroupUpdateOne) SetPhotoURL(s string) *GroupUpdateOne {
	guo.mutation.SetPhotoURL(s)
	return guo
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillablePhotoURL(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetPhotoURL(*s)
	}
	return guo
}

// SetUID sets the "uid" field.
func (guo *GroupUpdateOne) SetUID(s string) *GroupUpdateOne {
	guo.mutation.SetUID(s)
	return guo
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableUID(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetUID(*s)
	}
	return guo
}

// SetGroupCode sets the "group_code" field.
func (guo *GroupUpdateOne) SetGroupCode(s string) *GroupUpdateOne {
	guo.mutation.SetGroupCode(s)
	return guo
}

// SetNillableGroupCode sets the "group_code" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableGroupCode(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetGroupCode(*s)
	}
	return guo
}

// SetAccountID sets the "account_id" field.
func (guo *GroupUpdateOne) SetAccountID(u uuid.UUID) *GroupUpdateOne {
	guo.mutation.SetAccountID(u)
	return guo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableAccountID(u *uuid.UUID) *GroupUpdateOne {
	if u != nil {
		guo.SetAccountID(*u)
	}
	return guo
}

// SetAddress sets the "address" field.
func (guo *GroupUpdateOne) SetAddress(s string) *GroupUpdateOne {
	guo.mutation.SetAddress(s)
	return guo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableAddress(s *string) *GroupUpdateOne {
	if s != nil {
		guo.SetAddress(*s)
	}
	return guo
}

// ClearAddress clears the value of the "address" field.
func (guo *GroupUpdateOne) ClearAddress() *GroupUpdateOne {
	guo.mutation.ClearAddress()
	return guo
}

// SetIsActive sets the "is_active" field.
func (guo *GroupUpdateOne) SetIsActive(b bool) *GroupUpdateOne {
	guo.mutation.SetIsActive(b)
	return guo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableIsActive(b *bool) *GroupUpdateOne {
	if b != nil {
		guo.SetIsActive(*b)
	}
	return guo
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (guo *GroupUpdateOne) AddUserIDs(ids ...uuid.UUID) *GroupUpdateOne {
	guo.mutation.AddUserIDs(ids...)
	return guo
}

// AddUsers adds the "users" edges to the User entity.
func (guo *GroupUpdateOne) AddUsers(u ...*User) *GroupUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return guo.AddUserIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (guo *GroupUpdateOne) SetAccount(a *Account) *GroupUpdateOne {
	return guo.SetAccountID(a.ID)
}

// Mutation returns the GroupMutation object of the builder.
func (guo *GroupUpdateOne) Mutation() *GroupMutation {
	return guo.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (guo *GroupUpdateOne) ClearUsers() *GroupUpdateOne {
	guo.mutation.ClearUsers()
	return guo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (guo *GroupUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *GroupUpdateOne {
	guo.mutation.RemoveUserIDs(ids...)
	return guo
}

// RemoveUsers removes "users" edges to User entities.
func (guo *GroupUpdateOne) RemoveUsers(u ...*User) *GroupUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return guo.RemoveUserIDs(ids...)
}

// ClearAccount clears the "account" edge to the Account entity.
func (guo *GroupUpdateOne) ClearAccount() *GroupUpdateOne {
	guo.mutation.ClearAccount()
	return guo
}

// Where appends a list predicates to the GroupUpdate builder.
func (guo *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Group entity.
func (guo *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guo *GroupUpdateOne) check() error {
	if v, ok := guo.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := guo.mutation.Nickname(); ok {
		if err := group.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Group.nickname": %w`, err)}
		}
	}
	if v, ok := guo.mutation.Email(); ok {
		if err := group.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Group.email": %w`, err)}
		}
	}
	if v, ok := guo.mutation.PhoneNumber(); ok {
		if err := group.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Group.phone_number": %w`, err)}
		}
	}
	if v, ok := guo.mutation.PhotoURL(); ok {
		if err := group.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "Group.photo_url": %w`, err)}
		}
	}
	if v, ok := guo.mutation.UID(); ok {
		if err := group.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Group.uid": %w`, err)}
		}
	}
	if v, ok := guo.mutation.GroupCode(); ok {
		if err := group.GroupCodeValidator(v); err != nil {
			return &ValidationError{Name: "group_code", err: fmt.Errorf(`ent: validator failed for field "Group.group_code": %w`, err)}
		}
	}
	if v, ok := guo.mutation.Address(); ok {
		if err := group.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Group.address": %w`, err)}
		}
	}
	if guo.mutation.AccountCleared() && len(guo.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.account"`)
	}
	return nil
}

func (guo *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := guo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := guo.mutation.Nickname(); ok {
		_spec.SetField(group.FieldNickname, field.TypeString, value)
	}
	if value, ok := guo.mutation.Email(); ok {
		_spec.SetField(group.FieldEmail, field.TypeString, value)
	}
	if value, ok := guo.mutation.PhoneNumber(); ok {
		_spec.SetField(group.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := guo.mutation.PhotoURL(); ok {
		_spec.SetField(group.FieldPhotoURL, field.TypeString, value)
	}
	if value, ok := guo.mutation.UID(); ok {
		_spec.SetField(group.FieldUID, field.TypeString, value)
	}
	if value, ok := guo.mutation.GroupCode(); ok {
		_spec.SetField(group.FieldGroupCode, field.TypeString, value)
	}
	if value, ok := guo.mutation.Address(); ok {
		_spec.SetField(group.FieldAddress, field.TypeString, value)
	}
	if guo.mutation.AddressCleared() {
		_spec.ClearField(group.FieldAddress, field.TypeString)
	}
	if value, ok := guo.mutation.IsActive(); ok {
		_spec.SetField(group.FieldIsActive, field.TypeBool, value)
	}
	if guo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !guo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guo.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.AccountTable,
			Columns: []string{group.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.AccountTable,
			Columns: []string{group.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
