// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fast/ent/account"
	"fast/ent/group"
	"fast/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GroupCreate is the builder for creating a Group entity.
type GroupCreate struct {
	config
	mutation *GroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GroupCreate) SetName(s string) *GroupCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gc *GroupCreate) SetNillableName(s *string) *GroupCreate {
	if s != nil {
		gc.SetName(*s)
	}
	return gc
}

// SetNickname sets the "nickname" field.
func (gc *GroupCreate) SetNickname(s string) *GroupCreate {
	gc.mutation.SetNickname(s)
	return gc
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (gc *GroupCreate) SetNillableNickname(s *string) *GroupCreate {
	if s != nil {
		gc.SetNickname(*s)
	}
	return gc
}

// SetEmail sets the "email" field.
func (gc *GroupCreate) SetEmail(s string) *GroupCreate {
	gc.mutation.SetEmail(s)
	return gc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (gc *GroupCreate) SetNillableEmail(s *string) *GroupCreate {
	if s != nil {
		gc.SetEmail(*s)
	}
	return gc
}

// SetPhoneNumber sets the "phone_number" field.
func (gc *GroupCreate) SetPhoneNumber(s string) *GroupCreate {
	gc.mutation.SetPhoneNumber(s)
	return gc
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (gc *GroupCreate) SetNillablePhoneNumber(s *string) *GroupCreate {
	if s != nil {
		gc.SetPhoneNumber(*s)
	}
	return gc
}

// SetPhotoURL sets the "photo_url" field.
func (gc *GroupCreate) SetPhotoURL(s string) *GroupCreate {
	gc.mutation.SetPhotoURL(s)
	return gc
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (gc *GroupCreate) SetNillablePhotoURL(s *string) *GroupCreate {
	if s != nil {
		gc.SetPhotoURL(*s)
	}
	return gc
}

// SetUID sets the "uid" field.
func (gc *GroupCreate) SetUID(s string) *GroupCreate {
	gc.mutation.SetUID(s)
	return gc
}

// SetAddressID sets the "address_id" field.
func (gc *GroupCreate) SetAddressID(s string) *GroupCreate {
	gc.mutation.SetAddressID(s)
	return gc
}

// SetCreateTime sets the "create_time" field.
func (gc *GroupCreate) SetCreateTime(t time.Time) *GroupCreate {
	gc.mutation.SetCreateTime(t)
	return gc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (gc *GroupCreate) SetNillableCreateTime(t *time.Time) *GroupCreate {
	if t != nil {
		gc.SetCreateTime(*t)
	}
	return gc
}

// SetUpdateTime sets the "update_time" field.
func (gc *GroupCreate) SetUpdateTime(t time.Time) *GroupCreate {
	gc.mutation.SetUpdateTime(t)
	return gc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (gc *GroupCreate) SetNillableUpdateTime(t *time.Time) *GroupCreate {
	if t != nil {
		gc.SetUpdateTime(*t)
	}
	return gc
}

// SetGroupCode sets the "group_code" field.
func (gc *GroupCreate) SetGroupCode(s string) *GroupCreate {
	gc.mutation.SetGroupCode(s)
	return gc
}

// SetAccountID sets the "account_id" field.
func (gc *GroupCreate) SetAccountID(u uuid.UUID) *GroupCreate {
	gc.mutation.SetAccountID(u)
	return gc
}

// SetAddress sets the "address" field.
func (gc *GroupCreate) SetAddress(s string) *GroupCreate {
	gc.mutation.SetAddress(s)
	return gc
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (gc *GroupCreate) SetNillableAddress(s *string) *GroupCreate {
	if s != nil {
		gc.SetAddress(*s)
	}
	return gc
}

// SetIsActive sets the "is_active" field.
func (gc *GroupCreate) SetIsActive(b bool) *GroupCreate {
	gc.mutation.SetIsActive(b)
	return gc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (gc *GroupCreate) SetNillableIsActive(b *bool) *GroupCreate {
	if b != nil {
		gc.SetIsActive(*b)
	}
	return gc
}

// SetID sets the "id" field.
func (gc *GroupCreate) SetID(u uuid.UUID) *GroupCreate {
	gc.mutation.SetID(u)
	return gc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (gc *GroupCreate) SetNillableID(u *uuid.UUID) *GroupCreate {
	if u != nil {
		gc.SetID(*u)
	}
	return gc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (gc *GroupCreate) AddUserIDs(ids ...uuid.UUID) *GroupCreate {
	gc.mutation.AddUserIDs(ids...)
	return gc
}

// AddUsers adds the "users" edges to the User entity.
func (gc *GroupCreate) AddUsers(u ...*User) *GroupCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gc.AddUserIDs(ids...)
}

// SetAccount sets the "account" edge to the Account entity.
func (gc *GroupCreate) SetAccount(a *Account) *GroupCreate {
	return gc.SetAccountID(a.ID)
}

// Mutation returns the GroupMutation object of the builder.
func (gc *GroupCreate) Mutation() *GroupMutation {
	return gc.mutation
}

// Save creates the Group in the database.
func (gc *GroupCreate) Save(ctx context.Context) (*Group, error) {
	gc.defaults()
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GroupCreate) SaveX(ctx context.Context) *Group {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GroupCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GroupCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GroupCreate) defaults() {
	if _, ok := gc.mutation.Name(); !ok {
		v := group.DefaultName
		gc.mutation.SetName(v)
	}
	if _, ok := gc.mutation.Nickname(); !ok {
		v := group.DefaultNickname
		gc.mutation.SetNickname(v)
	}
	if _, ok := gc.mutation.CreateTime(); !ok {
		v := group.DefaultCreateTime()
		gc.mutation.SetCreateTime(v)
	}
	if _, ok := gc.mutation.UpdateTime(); !ok {
		v := group.DefaultUpdateTime()
		gc.mutation.SetUpdateTime(v)
	}
	if _, ok := gc.mutation.IsActive(); !ok {
		v := group.DefaultIsActive
		gc.mutation.SetIsActive(v)
	}
	if _, ok := gc.mutation.ID(); !ok {
		v := group.DefaultID()
		gc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GroupCreate) check() error {
	if v, ok := gc.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := gc.mutation.Nickname(); ok {
		if err := group.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Group.nickname": %w`, err)}
		}
	}
	if v, ok := gc.mutation.Email(); ok {
		if err := group.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Group.email": %w`, err)}
		}
	}
	if v, ok := gc.mutation.PhoneNumber(); ok {
		if err := group.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Group.phone_number": %w`, err)}
		}
	}
	if v, ok := gc.mutation.PhotoURL(); ok {
		if err := group.PhotoURLValidator(v); err != nil {
			return &ValidationError{Name: "photo_url", err: fmt.Errorf(`ent: validator failed for field "Group.photo_url": %w`, err)}
		}
	}
	if _, ok := gc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Group.uid"`)}
	}
	if v, ok := gc.mutation.UID(); ok {
		if err := group.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Group.uid": %w`, err)}
		}
	}
	if _, ok := gc.mutation.AddressID(); !ok {
		return &ValidationError{Name: "address_id", err: errors.New(`ent: missing required field "Group.address_id"`)}
	}
	if v, ok := gc.mutation.AddressID(); ok {
		if err := group.AddressIDValidator(v); err != nil {
			return &ValidationError{Name: "address_id", err: fmt.Errorf(`ent: validator failed for field "Group.address_id": %w`, err)}
		}
	}
	if _, ok := gc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Group.create_time"`)}
	}
	if _, ok := gc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Group.update_time"`)}
	}
	if _, ok := gc.mutation.GroupCode(); !ok {
		return &ValidationError{Name: "group_code", err: errors.New(`ent: missing required field "Group.group_code"`)}
	}
	if v, ok := gc.mutation.GroupCode(); ok {
		if err := group.GroupCodeValidator(v); err != nil {
			return &ValidationError{Name: "group_code", err: fmt.Errorf(`ent: validator failed for field "Group.group_code": %w`, err)}
		}
	}
	if _, ok := gc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "Group.account_id"`)}
	}
	if v, ok := gc.mutation.Address(); ok {
		if err := group.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Group.address": %w`, err)}
		}
	}
	if _, ok := gc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Group.is_active"`)}
	}
	if len(gc.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "Group.account"`)}
	}
	return nil
}

func (gc *GroupCreate) sqlSave(ctx context.Context) (*Group, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GroupCreate) createSpec() (*Group, *sqlgraph.CreateSpec) {
	var (
		_node = &Group{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(group.Table, sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID))
	)
	if id, ok := gc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gc.mutation.Nickname(); ok {
		_spec.SetField(group.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := gc.mutation.Email(); ok {
		_spec.SetField(group.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := gc.mutation.PhoneNumber(); ok {
		_spec.SetField(group.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := gc.mutation.PhotoURL(); ok {
		_spec.SetField(group.FieldPhotoURL, field.TypeString, value)
		_node.PhotoURL = value
	}
	if value, ok := gc.mutation.UID(); ok {
		_spec.SetField(group.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := gc.mutation.AddressID(); ok {
		_spec.SetField(group.FieldAddressID, field.TypeString, value)
		_node.AddressID = value
	}
	if value, ok := gc.mutation.CreateTime(); ok {
		_spec.SetField(group.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := gc.mutation.UpdateTime(); ok {
		_spec.SetField(group.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := gc.mutation.GroupCode(); ok {
		_spec.SetField(group.FieldGroupCode, field.TypeString, value)
		_node.GroupCode = value
	}
	if value, ok := gc.mutation.Address(); ok {
		_spec.SetField(group.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := gc.mutation.IsActive(); ok {
		_spec.SetField(group.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := gc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: []string{group.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := gc.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.AccountTable,
			Columns: []string{group.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupCreateBulk is the builder for creating many Group entities in bulk.
type GroupCreateBulk struct {
	config
	err      error
	builders []*GroupCreate
}

// Save creates the Group entities in the database.
func (gcb *GroupCreateBulk) Save(ctx context.Context) ([]*Group, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Group, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GroupCreateBulk) SaveX(ctx context.Context) []*Group {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GroupCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GroupCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
